"""
Conversation Memory API.

Provides endpoints for:
- Creating conversations
- Listing the current user's conversations
- Reading conversation history
- Reading conversation context
- Adding conversation turns
- Deleting conversations

All conversation access is restricted to the authenticated user.
"""

from __future__ import annotations

from uuid import uuid4

import json

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.agents.memory.agent import ConversationMemoryAgent
from app.core.database import get_db
from app.core.models import Conversation, ConversationMessage, User
from app.dependencies.auth import get_current_user


router = APIRouter(
    prefix="/conversations",
    tags=["Conversations"],
)

memory_agent = ConversationMemoryAgent()


# ---------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------


class ConversationTurnRequest(BaseModel):
    """
    Request body for adding a conversation turn.
    """

    user_query: str = Field(
        ...,
        min_length=1,
    )

    ai_response: str | None = None


# ---------------------------------------------------------------------
# Internal helper
# ---------------------------------------------------------------------


def _get_owned_conversation(
    conversation_id: str,
    current_user: User,
    db: Session,
) -> Conversation:
    """
    Return a conversation only when it belongs to the authenticated user.
    """

    conversation = (
        db.query(Conversation)
        .filter(
            Conversation.id == conversation_id,
            Conversation.user_id == current_user.id,
        )
        .first()
    )

    if conversation is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Conversation not found.",
        )

    return conversation


# ---------------------------------------------------------------------
# POST /conversations
# ---------------------------------------------------------------------


@router.post(
    "",
    status_code=status.HTTP_201_CREATED,
)
def create_conversation(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Create a new conversation for the authenticated user.

    The conversation ID is generated by the backend.
    The client does not provide the conversation ID.
    """

    conversation = Conversation(
        id=str(uuid4()),
        user_id=current_user.id,
    )

    try:
        db.add(conversation)
        db.commit()
        db.refresh(conversation)

    except Exception as error:
        db.rollback()

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to create conversation: {error}",
        ) from error

    return {
        "success": True,
        "conversation_id": conversation.id,
        "created_at": conversation.created_at,
        "updated_at": conversation.updated_at,
    }


# ---------------------------------------------------------------------
# GET /conversations
# ---------------------------------------------------------------------


@router.get("")
def list_conversations(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Return only conversations owned by the authenticated user.
    """

    conversations = (
        db.query(Conversation)
        .filter(
            Conversation.user_id == current_user.id,
        )
        .order_by(
            Conversation.updated_at.desc(),
        )
        .all()
    )

    return {
        "success": True,
        "count": len(conversations),
        "conversations": [
            {
                "conversation_id": conversation.id,
                "created_at": conversation.created_at,
                "updated_at": conversation.updated_at,
            }
            for conversation in conversations
        ],
    }


# ---------------------------------------------------------------------
# GET /conversations/{conversation_id}
# ---------------------------------------------------------------------


@router.get("/{conversation_id}")
def get_conversation(
    conversation_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Return a conversation and its messages only when owned
    by the authenticated user.
    """

    conversation = _get_owned_conversation(
        conversation_id=conversation_id,
        current_user=current_user,
        db=db,
    )

    messages = (
        db.query(ConversationMessage)
        .filter(
            ConversationMessage.conversation_id == conversation.id,
        )
        .order_by(
            ConversationMessage.created_at.asc(),
        )
        .all()
    )

    return {
        "success": True,
        "conversation_id": conversation.id,
        "created_at": conversation.created_at,
        "updated_at": conversation.updated_at,
        "messages": [
            {
                "id": message.id,
                "role": message.role,
                "content": message.content,
                "created_at": message.created_at,
                "message_metadata": (
                    json.loads(
                        message.message_metadata
                    )
                    if message.message_metadata
                    else {}
                ),
            }
            for message in messages
        ],
    }


# ---------------------------------------------------------------------
# GET /conversations/{conversation_id}/context
# ---------------------------------------------------------------------


@router.get("/{conversation_id}/context")
def get_conversation_context(
    conversation_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Return memory context for an owned conversation.
    """

    _get_owned_conversation(
        conversation_id=conversation_id,
        current_user=current_user,
        db=db,
    )

    context = memory_agent.get_context(
        db,
        conversation_id,
    )

    return {
        "success": True,
        "conversation_id": conversation_id,
        "context": context,
    }


# ---------------------------------------------------------------------
# POST /conversations/{conversation_id}/turns
# ---------------------------------------------------------------------


@router.post(
    "/{conversation_id}/turns",
    status_code=status.HTTP_201_CREATED,
)
def save_conversation_turn(
    conversation_id: str,
    request: ConversationTurnRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Save a conversation turn only to an owned conversation.
    """

    _get_owned_conversation(
        conversation_id=conversation_id,
        current_user=current_user,
        db=db,
    )

    try:
        memory_agent.store_turn(
            db=db,
            conversation_id=conversation_id,
            user_query=request.user_query,
            ai_response=request.ai_response,
        )

        return {
            "success": True,
            "conversation_id": conversation_id,
            "message": "Conversation turn saved successfully.",
        }

    except Exception as error:
        db.rollback()

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to save conversation turn: {error}",
        ) from error


# ---------------------------------------------------------------------
# DELETE /conversations/{conversation_id}
# ---------------------------------------------------------------------


@router.delete("/{conversation_id}")
def delete_conversation(
    conversation_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Delete only a conversation owned by the authenticated user.
    """

    conversation = _get_owned_conversation(
        conversation_id=conversation_id,
        current_user=current_user,
        db=db,
    )

    try:
        db.delete(conversation)
        db.commit()

        return {
            "success": True,
            "conversation_id": conversation_id,
            "message": "Conversation deleted successfully.",
        }

    except Exception as error:
        db.rollback()

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete conversation: {error}",
        ) from error