"""
Voice input handling.

The frontend performs speech recognition using the Web Speech API.
This module receives the resulting transcript and prepares it for
the existing query workflow.
"""

from typing import Optional

from .schemas import VoiceQueryRequest


class VoiceInputError(ValueError):
    """Raised when voice input is invalid."""

    pass


def validate_voice_query(
    transcript: str,
    conversation_id: Optional[str] = None,
    language: Optional[str] = "en-US",
) -> VoiceQueryRequest:
    """
    Validate raw voice-query data.

    Parameters
    ----------
    transcript:
        Text generated by the frontend Web Speech API.

    conversation_id:
        Identifier used to maintain conversation memory.

    language:
        Speech recognition language used by the frontend.

    Returns
    -------
    VoiceQueryRequest
        Validated voice-query request.

    Raises
    ------
    VoiceInputError
        If the transcript is empty or invalid.
    """

    try:
        request = VoiceQueryRequest(
            transcript=transcript,
            conversation_id=conversation_id,
            language=language,
            is_voice=True,
        )

        return request

    except ValueError as exc:
        raise VoiceInputError(str(exc)) from exc


def prepare_voice_query(request: VoiceQueryRequest) -> str:
    """
    Convert a validated voice request into the normal text query
    expected by the existing RAG workflow.

    The voice transcript is intentionally treated as ordinary text.

    Parameters
    ----------
    request:
        Validated VoiceQueryRequest.

    Returns
    -------
    str
        Cleaned transcript suitable for the existing /query workflow.
    """

    transcript = request.transcript.strip()

    if not transcript:
        raise VoiceInputError("Voice transcript cannot be empty.")

    return transcript