"""
Pydantic schemas for voice-query interaction.

The frontend uses the browser Web Speech API to convert speech
into text. Therefore, the backend receives a transcript rather
than an audio file.
"""

from typing import Optional

from pydantic import BaseModel, Field, field_validator


class VoiceQueryRequest(BaseModel):
    """
    Request received from the frontend for a voice query.

    The transcript is generated by the browser's Web Speech API.
    """

    transcript: str = Field(
        ...,
        min_length=1,
        description="Text transcript generated by the Web Speech API",
    )

    conversation_id: Optional[str] = Field(
        default=None,
        description="Conversation identifier used for multi-turn memory",
    )

    language: Optional[str] = Field(
        default="en-US",
        description="Language used for speech recognition",
    )

    is_voice: bool = Field(
        default=True,
        description="Indicates that the query originated from voice input",
    )

    @field_validator("transcript")
    @classmethod
    def validate_transcript(cls, value: str) -> str:
        """
        Remove unnecessary whitespace and reject empty transcripts.
        """

        value = value.strip()

        if not value:
            raise ValueError("Transcript cannot be empty.")

        return value

    @field_validator("conversation_id")
    @classmethod
    def validate_conversation_id(
        cls,
        value: Optional[str],
    ) -> Optional[str]:
        """
        Normalize the conversation ID if one is provided.
        """

        if value is None:
            return None

        value = value.strip()

        return value if value else None

    @field_validator("language")
    @classmethod
    def validate_language(
        cls,
        value: Optional[str],
    ) -> Optional[str]:
        """
        Normalize language information.
        """

        if value is None:
            return None

        value = value.strip()

        return value if value else "en-US"


class VoiceQueryResponse(BaseModel):
    """
    Optional response schema for voice-specific information.

    The actual answer/source/confidence fields should normally
    come from your existing M3 query response schema.
    """

    answer: str = Field(
        ...,
        description="Generated answer from the RAG workflow",
    )

    conversation_id: Optional[str] = Field(
        default=None,
        description="Conversation identifier",
    )

    sources: list = Field(
        default_factory=list,
        description="Sources returned by the retrieval pipeline",
    )

    confidence: Optional[float] = Field(
        default=None,
        description="Confidence score for the generated response",
    )

    clarification_required: bool = Field(
        default=False,
        description="Whether the workflow needs clarification",
    )

    clarification_question: Optional[str] = Field(
        default=None,
        description="Question to ask the user when clarification is required",
    )